# -*- coding: utf-8 -*-
"""Ejemplos_scapy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a2JQfQg2IpRNZsCeuSevLhWyl1vHKi1B
"""

# Ejemplo 1: ping a google
from scapy.all import *

# Enviar ping a Google y recibir respuesta
paquete = IP(dst="8.8.8.8") / ICMP()
respuesta = sr1(paquete, timeout=3, verbose=False)

if respuesta:
    print("¡Respuesta recibida!")
    print(f"IP de origen: {respuesta[IP].src}")
    print(f"Tipo ICMP: {respuesta[ICMP].type}")
else:
    print("No hubo respuesta")

# Ejemplo 2: captura de paquetes
from scapy.all import *

# Capturar 5 paquetes de la red
print("Capturando 5 paquetes...")
paquetes = sniff(count=5, timeout=10)

# Mostrar origen y destino de cada paquete
for i, paquete in enumerate(paquetes, 1):
    if paquete.haslayer(IP):
        print(f"Paquete {i}: {paquete[IP].src} -> {paquete[IP].dst}")
    else:
        print(f"Paquete {i}: No IP (puede ser ARP, etc.)")

print(f"Captura completada. {len(paquetes)} paquetes capturados.")